### ISSUE TITLE
Presentation about FISH 549

### ISSUE THREAD

**Issue by jhstern** [jhstern/Assignment-8#1]
I created an HTML presentation with the ioslides format in R Markdown. The presentation includes personal/academic information about myself, and it outlines some of the things I learned in class this quarter. The final slide is a photo of my cat, Della.

I am including a link to an HTML preview of my assignment slides on the off chance that the internet starts working again... 
[https://htmlpreview.github.io/?https://github.com/jhstern/Assignment-8/blob/main/Assignment-8-slides.html](https://htmlpreview.github.io/?https://github.com/jhstern/Assignment-8/blob/main/Assignment-8-slides.html)

**Comment by mdscheuerell** [comment]
Well done, Jenny. And it's always nice to see Della!
